### PR TITLE
linewise yanking and deleting behave correctly when operating at eof

### LINKED ISSUE #117: pasting linewise text at EOF is broken
Starting with the file (no newline at EOF):

```
abc
def
```

Pressing `yy` on the first line then pressing `p` on the last line should result in this file (again, no newline at EOF):

```
abc
def
abc
```

Instead we get this (with an extra newline at EOF):

```
abc
defabc
```

sorta related to #100

### PR DESCRIPTION
**Pull request by guillermooo**
Fixes #117 and #100.

### CODE REVIEW

**Comment by misfo** [comment]
Looks good!

One thing I just thought of. Does this Do The Right Thing when pasting over a selection that ends on the last line? If not, was that already broken?

**Comment by guillermooo** [comment]
After a quick look at vim, ST does not behave like it when pasting over charwise selections. It seems vim alwasy pastes `\ntext\n` in that case. To be honest, vim doesn't make sense to me here. I've just disovered this, so probably it's correct to say that this patch is actually broken.

**Comment by guillermooo** [comment]
BTW, the above assumes pasting from a register containing a newline at EOL.

**Comment by guillermooo** [comment]
I've combined the fixes for both issues again, b/c I don't see an easy way of separating both of them. My implementation is far from perfect, though. Currently we have at least two args in key bindings by the name of `linewise` confusingly serving similar purposes...

Also, this implementation creates suspicious special cases in `eval_input` and does a bit of args fumbling in `vi_eval`.

My impression is that the code handling this condition is too scattered, but I can't figure out a simpler way to solve this.

On the bright side, it seems to work for linewise ops, but I haven't tested charwise ops.

**Comment by guillermooo** [comment]
A summary of what this patch does.

## Fixes
1. `dd` and `yy` at EOF put `line\n` into register
2. `dd` removes last line completely
3. `Y` at EOF (and everywhere else) puts `line\n` into register (`D` does not seem to do this in Vim)
4. linewise pasting onto last line prefixes a `\n` to pasted text as Vim does and removes trailing `\n`
5. pasting whole lines onto charwise visual sel prefixes `\n` to pasted text as Vim does

## Limitations
- I don't think the patch currently distinguishes between linewise sels and charwise sels encompassing the whole last line. Actually, I don't think this is possible now without adding additional state to `g_input_state`.

## Bugs
- This seems to be unrelated to the patch: `u`ing a paste op onto a charwise visual sel gets stuck one level up.
- Others I have not detected yet, most likely...
- After pasting linewise at EOF, the caret remains at old EOF

**Comment by misfo** [comment]
> I don't think the patch currently distinguishes between linewise sels and charwise sels encompassing the whole last line. Actually, I don't think this is possible now without adding additional state to g_input_state.

`motion_mode` already holds that info:
https://github.com/sublimehq/Vintage/blob/master/vintage.py#L25

**Comment by guillermooo** [comment]
Hm... So `vi_copy` and `vi_delete` should receive that instead.

@misfo Have you tried the patch? Do you think this is the right direction?

**Comment by misfo** [comment]
Sorry if I'm being an ass, but can you get submit separate pulls for each separate fix? Or at least a separate commit for each fix? It's really hard to discuss fixes for multiple different issues if they're all smooshed together. It sounds like you found a few other EOF bugs, too. We should probably create an issue for each of those.

**Comment by guillermooo** [comment]
Haha, no worries. All these bugs being so closely related to each other, my head just tends to hurt  trying to figure out which one I'm fixing. I'll try to do that.

**Comment by misfo** [comment]
@guillermooo, I used your fix for #117 in the first commit in pull request #125. That should put a nail in that coffin.

We'll get your fixes for #100 and other EOF issues merged in next

**Pull request closed without merging**
