### PR TITLE
enabling half page motion commands as on Vim (ctrl + d / ctrl + u)

### PR DESCRIPTION
**Pull request by wilkerlucio**
I really use that ones, really missed when started using Vintage, but now I made it work, should be useful for other Vim users too.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
I would love this -- I use these commands in Vim all the time, and I can't use Vintage mode in ST2 without them!

**Comment by misfo** [comment]
This looks good to me, except that it doesn't jive with multiple selections. The transform_selection should move _all_ selections up/down half a page.

**Comment by misfo** [comment]
`ctrl+u` and `ctrl+d` have been merged into master in fa30a9dd5c8a7247362e747b0a70165a37d6db9b

**Comment by cocoanet** [comment]
Thank you , I need it.

**Pull request closed without merging**
