### PR TITLE
Cancel actions when 'Escape' is the motion

### PR DESCRIPTION
**Pull request by abrookins**
This patch cancels an action if 'Escape' is the motion command. E.g., the user starts to type a delete command (d) then hits Escape.

This behavior is essential for me (and follows Vim's). What do you think?

### CODE REVIEW

**Comment by abrookins** [comment]
Withdrawing this for now until I fix the vintage_ex issue.

**Comment by fjl** [comment]
i have addresed this issue in pull request #46. out of curiosity, why did you submit another version?

**Comment by abrookins** [comment]
Because it was late and I didn't read the the issue list closely enough to see that you'd already submitted a patch. I'm going to try yours and see if it fixes the issue I'm having with VintageEx mode.

**Comment by abrookins** [comment]
Awesome. Unlike my approach, your patch works with VintageEx!

**Pull request closed without merging**
