### PR TITLE
Added :x to save and close file

### PR DESCRIPTION
**Pull request by turboladen**
This is a Vim command I use pretty often--it'd be great to have it in here by default...

### CODE REVIEW

**Comment by dlo** [comment]
+1!

**Comment by marcusramberg** [comment]
This command exists in the ex addon tho?

**Comment by turboladen** [comment]
Hmm... that's helpful, I suppose, but seems more relevant to this plugin
than the command-line stuff that the ex plugin provides.  I don't have any
need for the ex plugin, so it'd be nice to have it here.

On Sun, Jul 8, 2012 at 6:33 AM, Marcus Ramberg <
reply@reply.github.com

**Comment by bronson** [comment]
Your patch is not valid JSON since you have duplicate keys ("command").  That doesn't work does it?  I'd guess the command either saves or closes but not both.

**Pull request closed without merging**
