### PR TITLE
Add text object motion 'vap' to visually select paragraph

### PR DESCRIPTION
**Pull request by behrends**

### CODE REVIEW

**Comment by sublimehq** [comment]
There appear to be a couple of unused elements here:

repeat: 1 in the key bindings doesn't appear to be required (the command doesn't use it)

outer = False (and the corresponding repeat = 1) in the command are both unused

It would be better to remove these.

**Comment by behrends** [comment]
Changed as suggested.

**Comment by sublimehq** [comment]
Thanks! Sorry to be a pain, but the ViExpandToParagraph class is no longer needed at all, the key binding can just set the motion to expand_selection_to_paragraph directly.

**Comment by behrends** [comment]
Right, no worries, I didn't see that. Changed.

**Pull request merged**
